In [1]:
from monkey.easy.decorators import easy_wrap, monkey_wrap
from monkey.easy.wrappers import EasyModel, MonkeyModel
from xgboost import XGBClassifier
from sklearn import datasets
import multiprocessing as mp
import numpy as np
np.set_printoptions(3)

iris = datasets.load_iris()

X = iris['data']
y = iris['target']
print(X.shape)


(150, 4)


## Easy Wrap Example

In [2]:
xgb = XGBClassifier()
model = xgb.fit(X, y)

In [3]:
@easy_wrap(model, "xgb-example", path=".models/")
def invoke_model(X, model):
    print("I would like to invoke the model")
    return model.predict(X)

In [4]:
new_model = EasyModel("xgb-example")
new_model.predict(X)

I would like to invoke the model


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
%ls -la .models/xgb-example

total 232
drwxr-xr-x  4 502  staff     128 Nov 24 08:51 ./
drwxr-xr-x  8 502  staff     256 Nov 24 14:56 ../
-rw-r--r--  1 502  staff     319 Nov 24 15:10 xgb-example-wrapper.pkl
-rw-r--r--  1 502  staff  112630 Nov 24 15:10 xgb-example.pkl


In [6]:
@easy_wrap(model, "xgb-example2", path=".models/")
def invoke_model(X, model):
    print("I would like to invoke the model w/ predict_proba")
    return model.predict_proba(X)

In [7]:
new_model = EasyModel("xgb-example2")
new_model.predict(X)

I would like to invoke the model w/ predict_proba


array([[0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.993, 0.005, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.993, 0.005, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.983, 0.015, 0.002],
       [0.983, 0.015, 0.002],
       [0.993, 0.005, 0.002],
       [0.994, 0.004, 0.002],
       [0.983, 0.015, 0.002],
       [0.994, 0.004, 0.002],
       [0.993, 0.005, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.993, 0.005, 0.002],
       [0.993, 0.005, 0.002],
       [0.994, 0.004, 0.002],
       [0.994, 0.004, 0.002],
       [0.993, 0.005, 0.002],
       [0.993, 0.005, 0.002],
       [0.

In [8]:
%ls -la .models/xgb-example2

total 232
drwxr-xr-x  4 502  staff     128 Nov 24 08:59 ./
drwxr-xr-x  8 502  staff     256 Nov 24 14:56 ../
-rw-r--r--  1 502  staff     342 Nov 24 15:10 xgb-example2-wrapper.pkl
-rw-r--r--  1 502  staff  112630 Nov 24 15:10 xgb-example2.pkl


## Monkey Wrap Example

In [9]:
from sklearn.ensemble import GradientBoostingClassifier

In [10]:
gbe = GradientBoostingClassifier()
model2 = gbe.fit(X, y)

### Multiple Models

In [11]:
@monkey_wrap([model, model2], [], model_name="xgb-gbe-example", path=".models/")
def invoke_model(X, models, artifacts):
    print("I would like to invoke both models")
    model_0 = models["model-object-0"]; model_1 = models["model-object-1"]
    pred_0 = model_0.predict_proba(X); pred_1 = model_1.predict_proba(X)
    score = (pred_0+pred_1)/2.
    return score

In [12]:
%%time
new_model2 = MonkeyModel("xgb-gbe-example",  path=".models/")
new_model2.predict(X)

I would like to invoke both models
CPU times: user 11.2 ms, sys: 2.6 ms, total: 13.8 ms
Wall time: 12.8 ms


array([[9.970e-01, 2.149e-03, 8.406e-04],
       [9.969e-01, 2.053e-03, 1.006e-03],
       [9.971e-01, 2.094e-03, 8.402e-04],
       [9.971e-01, 2.094e-03, 8.386e-04],
       [9.970e-01, 2.149e-03, 8.406e-04],
       [9.965e-01, 2.690e-03, 8.397e-04],
       [9.971e-01, 2.094e-03, 8.407e-04],
       [9.970e-01, 2.149e-03, 8.406e-04],
       [9.969e-01, 2.053e-03, 1.006e-03],
       [9.971e-01, 2.094e-03, 8.386e-04],
       [9.965e-01, 2.690e-03, 8.397e-04],
       [9.971e-01, 2.094e-03, 8.407e-04],
       [9.969e-01, 2.053e-03, 1.006e-03],
       [9.969e-01, 2.053e-03, 1.006e-03],
       [9.914e-01, 7.769e-03, 8.313e-04],
       [9.914e-01, 7.769e-03, 8.313e-04],
       [9.965e-01, 2.690e-03, 8.397e-04],
       [9.970e-01, 2.149e-03, 8.406e-04],
       [9.914e-01, 7.769e-03, 8.313e-04],
       [9.970e-01, 2.149e-03, 8.406e-04],
       [9.965e-01, 2.690e-03, 8.397e-04],
       [9.970e-01, 2.149e-03, 8.406e-04],
       [9.971e-01, 2.094e-03, 8.407e-04],
       [9.970e-01, 2.149e-03, 8.40

In [13]:
%ls -la .models/xgb-gbe-example

total 880
drwxr-xr-x  5 502  staff     160 Nov 24 14:56 ./
drwxr-xr-x  8 502  staff     256 Nov 24 14:56 ../
-rw-r--r--  1 502  staff  112630 Nov 24 15:10 xgb-gbe-example-model-object-0.pkl
-rw-r--r--  1 502  staff  301328 Nov 24 15:10 xgb-gbe-example-model-object-1.pkl
-rw-r--r--  1 502  staff     516 Nov 24 15:10 xgb-gbe-example-wrapper.pkl
